### ISSUE TITLE
All calculations are wrong !

### ISSUE THREAD

**Issue by zyo00ody** [mourner/suncalc#101]
I've tested all functions in SunCalc and I compared it with accurate websites and programs, and I've found all calculations are wrong ! (moon rise-set, moon illumination, distance, position, sun position)

**Comment by zyo00ody** [comment]
Now the correct distance between Moon and Earth is : 
http://www.mooncalc.org    (368568 km)

SunCalc.getMoonPosition(new Date(), 0, 0).distance    (372684 km)

**Comment by mourner** [comment]
OK, congratulations. Please use other libraries.

**Comment by zyo00ody** [comment]
Sorry but I don't know what is the problem. 
All times and functions gives me far and wrong values.

**Comment by stephenpaulger** [comment]
It might be more useful if you gave examples of how you obtained an incorrect value, what value you expected and how you obtained it.

**Comment by zyo00ody** [comment]
I've tested Moon rise and set times, and Moon distance, and Moon phase, and Sun rise and set times, and Moon position, and Sun position.
In any location in the world, all gives me wrong values compared with many websites like:
http://www.mooncalc.org/
http://www.suncalc.org/
and many accurate programs all gives the same value, and suncalc gives different values.   

Sorry for my bad English

**Comment by Madeck** [comment]
@zyo00ody, [suncalc.ORG](http://suncalc.org/) and [suncalc.NET](http://suncalc.net/) have only minimal divergence. A couple of seconds here or there, but you would have to provide a reason for one being superior, or ”more precise” than the other.

Currently one could simply tell you all the software you use are inaccurate. Especially as you're not even mentioning which one they are.

**Comment by zyo00ody** [comment]
@Madeck No.
There are big deterrent in All values except sun rise and set may be close to the correct time.
I'm working on very accurate project and I've tested suncalc .. These values are not accurate : 
(moon distance, moon position, sun position, moon illumination)
Good luck

**Comment by stefanocudini** [comment]
@mourner 
Have patience but I have the same problem...
in my case for a location nearby Rome, Italy I run this at browser console(latest Chrome)
```javascript
SunCalc.getTimes(new Date('2017-7-25'), 41.863553, 12.597231).sunset
Tue Jul 25 2017 17:36:49 GMT-0100 (-01)
```

**Comment by mourner** [comment]
@stefanocudini you have a different location in your second link. If you update it with the first one, it's only a ~2 min difference.

**Comment by stefanocudini** [comment]
@mourner 
Sorry Now I've tried using the same location and this and it too wrong the times
```
SunCalc.getTimes(new Date('2017-7-25'), 41.8368,12.7441).sunset
Tue Jul 25 2017 17:36:10 GMT-0100 (-01)
```

**Comment by mourner** [comment]
@stefanocudini it looks like a correct result to me — note that it displays the time formatted in your current timezone, not the timezone of the specified location. This is expected.

**Comment by stefanocudini** [comment]
I resolve adding "3" to the hours... but I don't understand how calculate "3" beacause my getTimezoneOffset is only "1"

```javascript
	var loc = [41.8368,12.7441];
	var now = new Date(),
		utc = new Date(now.getTime() + now.getTimezoneOffset() * 60000),
		times = SunCalc.getTimes(now, loc[0], loc[1]);

	function format(date) {
		date.setHours(date.getHours() + 3);
		return date.toTimeString().slice(0,5);
	}

	sunrise = format(times.sunrise),
	sunset  =format(times.sunset)
```

**Comment by zyo00ody** [comment]
@stefanocudini I advise you not to use SunCalc if you are working on accurate project, see this is a bug in it https://github.com/mourner/suncalc/issues/102 , 
use https://github.com/Fabiz/MeeusJs  while @mourner fix SunCalc errors.

Thank you and sorry for my bad English .

**Comment by Haixiang6123** [comment]
@aoizoijoizj @stefanocudini  hey, I also have the same problem with using geojson. But I find the reason is because I use the opposite position.

So in Geojson, the coordinates is [longitude, latitude], but for `SunCalc.getTimes` function is latitude comes first.

Not sure if this is you guys problem too.

**Comment by aoizoijoizj** [comment]
@Haixiang6123 @stephenpaulger 
Hello again
Don't waste your time. The real problem is in the equations used in this library which is has very low accuracy and doesn't account for delta-T and many other effects.

If you want more accuracy use [**MeeusJs**](https://github.com/Fabiz/MeeusJs/tree/master/lib) 

And if you want very high accuracy use **full VSOP** theory for sun calculations, and complete **ELP-2000 theory** for moon calculations. You can find those in GitHub.
 Thank you
