### ISSUE TITLE
Inaccuracy in solar mean anomaly calculation

### ISSUE THREAD

**Issue by NaanProphet** [mourner/suncalc#110]
I'm not sure, but I think there may be a typo in lines 147-149. `solarMeanAnomaly(ds)` should be `solarMeanAnomaly(d)`:

```
        ds = approxTransit(0, lw, n),

        M = solarMeanAnomaly(ds),
```

## Derivation

As per equation 1 on this resource by [Astronomy Answers](http://aa.quae.nl/en/reken/zonpositie.html), the solar mean anomaly is computed using the Julian date. Screenshot for reference below:

![screen shot 2018-01-06 at 1 46 28 pm](https://user-images.githubusercontent.com/2568736/34642851-38c3c506-f2e8-11e7-894d-28c5e8b77476.png)

## Conflicting Correct Usage

Also, in other places of `suncalc.js` the Julian date is used in calculation, further suggesting that passing in `ds` instead of `d` on line 149 was a typo:

```
# lines 84-90
SunCalc.getPosition = function (date, lat, lng) {

    var lw  = rad * -lng,
        phi = rad * lat,
        d   = toDays(date),

        c  = sunCoords(d),

# lines 67-69
function sunCoords(d) {

    var M = solarMeanAnomaly(d)
```

While the difference is small, it would still seem good to correct.

**Comment by mourner** [comment]
The calculation is correct. See point 3 of "Solar Transit" section, specifically "calculate M and Lsun for Jx":

![image](https://user-images.githubusercontent.com/25395/34654013-1e631d6c-f3fe-11e7-8af4-d53870400437.png)

**Comment by NaanProphet** [comment]
Ah, thanks very much! I saw eq. 34 before with the higher order corrections for J<sub>transit</sub> but missed catching that `M` in that equation was recalculated _for_ J<sub>x</sub>

:)
