### ISSUE TITLE
null result

### ISSUE THREAD

**Issue by p-3** [mourner/suncalc#127]
i am getting null result on sunrise, sunset and golden hour with Lat:67.8557995, Lng:20.225282, Date:  Dec 18 2018 21:23

{
"solarNoon": "2018-12-18T10:36:55.250Z",
"nadir": "2018-12-17T22:36:55.250Z",
"sunrise": null,
"sunset": null,
"sunriseEnd": null,
"sunsetStart": null,
"dawn": "2018-12-18T07:54:54.543Z",
"dusk": "2018-12-18T13:18:55.957Z",
"nauticalDawn": "2018-12-18T06:26:52.344Z",
"nauticalDusk": "2018-12-18T14:46:58.157Z",
"nightEnd": "2018-12-18T05:15:55.029Z",
"night": "2018-12-18T15:57:55.472Z",
"goldenHourEnd": null,
"goldenHour": null
}

**Comment by mourner** [comment]
This is because sunrise/sunset never happen at that latitude and date. https://en.wikipedia.org/wiki/Polar_night
