### ISSUE TITLE
Moon Illumination calculation with atan

### ISSUE THREAD

**Issue by jason4short** [mourner/suncalc#131]
inc = Math.atan(sdist * Math.sin(phi), m.dist - sdist * Math.cos(phi))

Just curious why this calc is an atan with two arguments when atan only takes 1 argument. The second argument is ignored. 

thanks
Jason

**Comment by mourner** [comment]
https://github.com/mourner/suncalc/blob/master/suncalc.js#L16

**Comment by jason4short** [comment]
Ha, when I ported the code, I missed that. A little confusing since the compiler happily takes two values.
