### ISSUE TITLE
Put links back to this GitHub on the websites.

### ISSUE THREAD

**Issue by jidanni** [mourner/suncalc#132]
Is this GitHub related to https://www.suncalc.org/ ?
If so please put a link on the latter to the former.
If we knew it was open source, we would want to use it more.
Same with the Android app.

**Comment by mourner** [comment]
> Is this GitHub related to https://www.suncalc.org/ ?
No.

**Comment by jidanni** [comment]
Well it looks rather similar. So I would add a FAQ item saying the lack
of relationship, or that it is just a coincidence.
