### ISSUE TITLE
getMoonTimes results in alwaysUp while it should be AlwaysDown

### ISSUE THREAD

**Issue by HansR00** [mourner/suncalc#142]
getMoonTimes results in alwaysUp while it should be AlwaysDown (ref: mooncalc.org) when calculating for Latitude = 70; Longitude = 6.9314; on 10th of may 2020.

As a result programmatic decisions fail.

**Comment by zedxxx** [comment]
Why did you close issue?

**Comment by HansR00** [comment]
Because there is no response in almost two years and I am cleaning up.
