### ISSUE TITLE
Height Units?

### ISSUE THREAD

**Issue by Xeonzinc** [mourner/suncalc#153]
Hi,

I can see the height parameter has been added as an optional input, but it doesn't seem to say anywhere what units this should be input in? Meters? Kilometers? AU?

**Comment by ay8s** [comment]
@Xeonzinc Looks like it's meters. https://github.com/mourner/suncalc/blob/031c4ad3f6f330a02863ec0f43b820115294ccca/suncalc.js#L140

**Comment by Xeonzinc** [comment]
Thanks, good spot!
