### ISSUE TITLE
Suncalc is awesome!

### ISSUE THREAD

**Issue by hollingberry** [mourner/suncalc#31]
Do you mind if I work on a Ruby port?

**Comment by warpling** [comment]
[Objective-C port](https://github.com/swerdlow/suncalc-objective-c)
[Swift port](https://github.com/shanus/suncalc-swift)

**Comment by mourner** [comment]
Thanks! I think I'll add a section in the readme with links to ports.

**Comment by aubergine10** [comment]
https://github.com/florianmski/SunCalc-Java

https://github.com/mncaudill/SunCalc-Java

https://github.com/mourner/suncalc-go I'm guessing you already know this one :P 

https://github.com/shanus/suncalc-swift 

https://github.com/mateusmaso/suncalc-ruby

https://github.com/RandomEtc/suncalc-api
