### ISSUE TITLE
Moon Rise / Set is backwards ?

### ISSUE THREAD

**Issue by JesseScott** [mourner/suncalc#39]
I am passing in my local time (PST) and GPS location (for Vancouver) and this is the object I am getting back for getMoonTimes(): 

*Object {rise: Sat Feb 07 2015 04:28:44 GMT-0800 (PST), set: Sat Feb 07 2015 16:39:38 GMT-0800 (PST)}*

How does this makes sense that the moon rises after 4am and sets at 4pm? I am looking outside and I can *see* the moon!

I think that these are being returned in the wrong order... 

And... Thanks for the wonderful library!

**Comment by mourner** [comment]
Probably some error in your code. Here's how it works for me:

```
s.getMoonTimes(Date.now(), 49.246292, -123.116226)
{ rise: Sat Feb 07 2015 06:34:23 GMT+0200 (EET),
  set: Sat Feb 07 2015 18:56:38 GMT+0200 (EET) }
```

Which is within 2 minutes from what http://www.timeanddate.com/moon/canada/vancouver says for today.

**Comment by JesseScott** [comment]
I know you closed this, but you're right - it was an error on my part (or rather, two errors possibly)... I was passing *new Date()* into the first argument, and didnt have the *minus* in front of the Longitude... 

Sorry, should have debugged better myself beforehand... just wanted to post here to make sure there was no confusion for anyone else that may see this at a later time...
