### ISSUE TITLE
"SunCalc.getTimesBetween" call?

### ISSUE THREAD

**Issue by ironwallaby** [mourner/suncalc#43]
So many <3 for SunCalc. Thanks again for providing it.

I am interested in a rather different API call: I'd like to provide a location, start date, and end date, and get all "events" that happen between those times. That is, for each of the following:

*   sunrise
*   sunriseEnd
*   goldenHourEnd
*   solarNoon
*   goldenHour
*   sunsetStart
*   sunset
*   dusk
*   nauticalDusk
*   night
*   nadir
*   nightEnd
*   nauticalDawn
*   dawn
*   moonrise
*   moonset
*   newMoon
*   firstQuarterMoon
*   fullMoon
*   thirdQuarterMoon

I'd like a list to be generated and returned for every one of the above events that happens between those two dates (inclusive). (It'd be *especially* nice if I could select, using an optional object, which properties I care about, in order to cut down on unnecessary computations...)

This might be something that's starting to get a little out-of-scope of the project; but on the other hand, one could conceivably implement the SunCalc.getTimes function in terms of this one, so maybe it's a 2.0 thing (that is, a change in API).

**Comment by ironwallaby** [comment]
(I just realized that equinoxes and solstices would be another nice-to-have, so long as it can reuse the same machinery.)

**Comment by mourner** [comment]
You could do the same with a simple `for` loop, right? I'm not sure this is worth doing as a part of suncalc API, as it's already simple and easy enough to use for this kind of things.

**Comment by ironwallaby** [comment]
How would that work: call SunCalc.getTimes (and SunCalc.getMoonTimes) in a loop starting from the date of the first time and incrementing by 24 hours each time?

**Comment by mourner** [comment]
Yes, exactly.

**Comment by ironwallaby** [comment]
Understood. I'll give that a shot; thanks!
