### ISSUE TITLE
No night/end calculations for specific place and date

### ISSUE THREAD

**Issue by GermanBluefox** [mourner/suncalc#44]
Following place and date give no "night/nightEnd"
http://suncalc.net/#/50.6252,12.9239,13/2015.06.01/23:29

Why?

00:00—  n/a   — night
  n/a  —03:16 — astronomical twilight
03:16—04:19 — nautical twilight
04:19—05:02 — civil twilight
05:02—05:07 — sunrise
05:07—21:07 — daylight
21:07—21:12 — sunset
21:12—21:55 — civil twilight
21:55—22:58 — nautical twilight
22:58—  n/a   — astronomical twilight
  n/a  —00:00 — night

**Comment by mourner** [comment]
Because sun does not go deep enough below the horizon for the sky to go completely dark, so there's no astronomical night.
