### ISSUE TITLE
Real Time Sun Movement

### ISSUE THREAD

**Issue by spencerthayer** [mourner/suncalc#46]
I would like to move a representation of the sun and the moon and an x and y axis across the browser runtime in real time in a manner similar to the attached photograph. However I cannot find the correct calculations.

How did you represent the suns movement on a flat X Y plane for suncalc.net?

![10389967_10206442225590678_5409985522669922473_n 1](https://cloud.githubusercontent.com/assets/1019815/8211231/99a52d8a-14db-11e5-9887-8bd9fffcb98f.jpg)

**Comment by mourner** [comment]
Well, x axis is azimuth, y axis is altitude. Both are returned by suncalc. So I don't really understand the question.
