### ISSUE TITLE
Validity of the constants

### ISSUE THREAD

**Issue by cmkpl** [mourner/suncalc#47]
Thanks for creating such great program. I would like to know:

1. What is the accuracy of the constants?
2. where can we find the up-to-date values of constants so that we can update them year by year?

**Comment by mourner** [comment]
You should ask the authors of http://aa.quae.nl/en/reken/zonpositie.html about this. I don't know how up to date are the constants, but I know that it's enough to have a precision within a 1-2 minutes.
