### ISSUE TITLE
SunCalc.getMoonTimes returns object with no "set" property

### ISSUE THREAD

**Issue by jspeaker** [mourner/suncalc#48]
This issue appears to be related to the closed issue: No moonrise/moonset when moon rises after midnight #37

When the moon set time should be within the hour after midnight, no set property gets returned. I would expect from the code this would also be the case with moon rise.

Following is a call with exact date and coordinates to reproduce the issue.

currentDate = Sun Jun 21 2015 00:00:00 GMT-0700 (Pacific Daylight Time)
mapSettings.latitude = 48.41894
mapSettings.longitude = -122.63909999999998

SunCalc.getMoonTimes(currentDate, mapSettings.latitude, mapSettings.longitude);

This returns a moonTimes object with a rise property only.

As discussed in the referenced issue, it appears that line 253 is off by 1.
253:     for (var i = 1; i <= 24; i += 2) {

The hours of the day are 0  - 23, not 1 - 24 as this for loop suggests.
Changing this line to the following rectifies the problem:
253:         for (var i = 0; i < 24; i += 2) {
OR
253:         for (var i = 0; i <= 23; i += 2) {

**Comment by jspeaker** [comment]
I jumped the gun on this issue. There is no moon set on the date I provided at those coordinates. It does not set until the next day (just after midnight), and rises in the morning at 10:43 am. Sorry to bother you! Cheers

**Comment by mourner** [comment]
Thanks :)

**Comment by The-Best-Codes** [comment]
Sorry, I don't fully understand all this. How could I make it still give me a moonrise and moonset for the current date, and if it is the next day, then correct itself? Best Regards!
