### ISSUE TITLE
moon rise date earlier than moon set date

### ISSUE THREAD

**Issue by rdbcci** [mourner/suncalc#55]
SunCalc.getMoonTimes is based on http://www.stargazing.net/kepler/moonrise.html and that algorithm returns a relative moon rise and moon set. So for instance, at 45 lat and -92.12 lon on 20151028 SunCalc.getMoonTimes returns that the moon rise is Wed Oct 28 2015 19:22:01 GMT-0500 (Central Daylight Time) and the moon set is Wed Oct 28 2015 08:58:15 GMT-0500 (Central Daylight Time). These times are relatively correct, but the moon rise date returned is later than the moon set date returned. The fix is to add 24 to the moon set hours parameter of the hoursLater function call to get the result.set to return when the moon rise hours parameter is greater  than the moon set hours.

**Comment by mourner** [comment]
The issue is due to timezone differences. I'm releasing 1.7.0 with `inUTC` argument that's explained here: https://github.com/mourner/suncalc#moon-rise-and-set-times, it should address the issue.

**Comment by rdbcci** [comment]
I may have missed something, but I think my fix is easier and since SunCalc.getMoonTimes returns javascript Date objects, user could get universal time from the getUTC methods already.

**Comment by rdbcci** [comment]
Never mind, I think I get it now. Moon rise and moon set are for a particular date. Date objects returned are for particular date. For a particular date, moon rise is only earlier then moon set when it occurs on the same day. Otherwise, the moon set is from when it rose the previous day. I believe that is why the algorithm must return that the moon may not rise or set on a particular day for each lunation cycle.

As far as inUTC, that is just a longitude near 0. So I would not think that is required.
