### ISSUE TITLE
moon rise error

### ISSUE THREAD

**Issue by charleswilt** [mourner/suncalc#56]
Moon rise time returned undefined today.
Moon set is fine.

**Comment by mourner** [comment]
For what location? Are you sure this is wrong result? Did you compare it with sites like timeanddate world clock?

**Comment by charleswilt** [comment]
It was for Denver, Colorado at 39 and -104 for November 4th. Works fine
today November 5th.

On Thu, Nov 5, 2015 at 1:55 AM, Vladimir Agafonkin <notifications@github.com

**Comment by mourner** [comment]
As you can see here http://www.timeanddate.com/moon/usa/denver, there was no moonrise on Nov 4.

**Comment by charleswilt** [comment]
I see. Completely did not consider that. I will remove the bug report

**Comment by jspeaker** [comment]
It seems we've all thought that was a bug at one time or another. I filed a similar bug report some time ago... ;)
