### ISSUE TITLE
Ported to Haxe.

### ISSUE THREAD

**Issue by ypid** [mourner/suncalc#58]
Hi

I just wanted to let you know that I have ported your library to Haxe: https://github.com/ypid/suncalc

Haxe allows to target multiple languages. The reason for this is [that I want to rewrite opening_hours.js in Haxe](https://github.com/opening-hours/opening_hours.js/issues/136).

If you plan on adding new features you now have the option to either implement them in Haxe or in JavaScript as Haxe can easily target js and your `test.js` is passing with the transcomipled version from Haxe. But you don’t have to do that. I am going to maintain the Haxe port and might port features/bugfixes from you to it.

Thanks for writing this library :+1:

**Comment by mourner** [comment]
Cool, thanks!
