### ISSUE TITLE
No time zones - Results in overflow error.

### ISSUE THREAD

**Issue by Sarah-C** [mourner/suncalc#65]
When the longitude is over about 100 or less than -100  (range is -180 to 180), the day/night zones do not occur during the GMT day the calculations plot.

This makes the following calculation become less than -1.0000:

(Math.Sin(h) - Math.Sin(phi) * Math.Sin(dec)) / (Math.Cos(phi) * Math.Cos(dec))

So when Math.Acos([the above]) is used - NaN occurs because the result is out of range for arcCos (-1 to 1)

Adding an input for time zones would mean the calculation would always be in range if the inputs are used correctly.

**Comment by mourner** [comment]
Can you share a specific code that produces the error?

**Comment by Sarah-C** [comment]
Something like the following would cause the error:
Sun.SunCalcGetTimes(new Date(2016,01,01), 50, -100)

I've implemented the code in .Net, in a chart, so I don't have an example code fragment to show you - I will put one together when I'm not in work. It's end of break now. I'll make sure to use JavaScript.

When it works - where I live in the UK:
![When it works:](http://i.imgur.com/TIlmKfZ.png)

A problem location:
![Problem location:](http://i.imgur.com/pDxKjaa.png)

**Comment by mourner** [comment]
Are you sure that's a problem in suncalc calculations and not your visualization?

**Comment by Sarah-C** [comment]
You're right, I've just wrote a test platform in JavaScript for Chrome using the TAP test script you have.

I got all "Passed", so I changed the lat/long to extremes - there is NO ERROR.

Please discard this thread, sorry for assuming there was an issue.

**Comment by Sarah-C** [comment]
I've just double checked in JavaScript - there IS an error.
I've attached a test webpage.

Using the following location info:

var date = new Date('2013-03-05UTC');
    lat = 89,
    lng = 179;

w is NaN here, and the calculations fail:

// returns set time for the given sun altitude
function getSetJ(h, lw, phi, dec, n, M, L) {
    var w = hourAngle(h, phi, dec),
        a = approxTransit(w, lw, n);
    return solarTransitJ(a, M, L);
}


Test results:

getTimes returns sun phases for the given date and location
Failed : [solarNoon] : Tue, 05 Mar 2013 10:10:57 GMT = Tue, 05 Mar 2013 00:17:02 GMT
Failed : [nadir] : Mon, 04 Mar 2013 22:10:57 GMT = Mon, 04 Mar 2013 12:17:02 GMT
Failed : [sunrise] : Tue, 05 Mar 2013 04:34:56 GMT = Invalid Date
Failed : [sunset] : Tue, 05 Mar 2013 15:46:57 GMT = Invalid Date
Failed : [sunriseEnd] : Tue, 05 Mar 2013 04:38:19 GMT = Invalid Date
Failed : [sunsetStart] : Tue, 05 Mar 2013 15:43:34 GMT = Invalid Date
Failed : [dawn] : Tue, 05 Mar 2013 04:02:17 GMT = Mon, 04 Mar 2013 18:53:02 GMT
Failed : [dusk] : Tue, 05 Mar 2013 16:19:36 GMT = Tue, 05 Mar 2013 05:41:03 GMT
Failed : [nauticalDawn] : Tue, 05 Mar 2013 03:24:31 GMT = Invalid Date
Failed : [nauticalDusk] : Tue, 05 Mar 2013 16:57:22 GMT = Invalid Date
Failed : [nightEnd] : Tue, 05 Mar 2013 02:46:17 GMT = Invalid Date
Failed : [night] : Tue, 05 Mar 2013 17:35:36 GMT = Invalid Date
Failed : [goldenHourEnd] : Tue, 05 Mar 2013 05:19:01 GMT = Invalid Date
Failed : [goldenHour] : Tue, 05 Mar 2013 15:02:52 GMT = Invalid Date


[SunCalc.txt](https://github.com/mourner/suncalc/files/95893/SunCalc.txt)

**Comment by mourner** [comment]
Thanks for the test case Sarah! I will look into it.

**Comment by Sarah-C** [comment]
I don't have the math to understand what's going on for the ACos function
to have a parameter that's out of range.

A work around I'm looking at is getting the time zone (-11 to +11 hours)
and using that to alter the longitude before it's passed to the sun times
calculation engine.

There's a nice lat/long to timezone program here that doesn't need the
program to be online (no web services!)
http://davidegironi.blogspot.co.uk/2014/03/finding-timezone-by-latitude-longitude.html#.Vp9hz_mLTRY

Sadly, it only produces the name of the timezone, so it needs looking up in
the tz Database TZ list:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


Worldwide Daylight Saving Time is out of the question - each country has
it's own rules as to when it starts and ends! So that would need to be a
user setting (or perhaps using the location API's on the platform being
developed). Phones the world over know when to start and end DST...

The time zone query doesn't work for water masses either!

Sometimes the simplest solution using a fair amount of memory is the best -
I believe mapping latitude and longitude to an -image- would be
sufficiently accurate (borders excluded)

Such as this: http://www.csd.uwo.ca/~jamie/.Refs/timezone-map.html
or http://www.nrgi.fr/acc/objet/TimeZoneMap2.jpg
But in mega high resolution without the landmasses being visible, then ALL
locations on the ocean can have a timezone, and everywhere but borders on
land would be easy. It would just need the pixel for the given lat/long
read out.

I did a naive test for my time-zone solution (adjusting longitude by
timezone before the sun calculation), I scanned across the equator in my
chart, looking at the day profile. It did not change according to my
blinkless stare.

I then moved up to the pole, and scanned again (from -170ish to +170
ish)... watching the profile of the sunrise sunset chart again confirmed
even at this longitude the overall profile didn't change, even for extremes
of longitude.

Therefore I should be able to normalise the longitude around Greenwich, by
adjusting the longitude based on the timezone (each 1 hour is 15 in the
decimalised longitude, +12 time zone ("back" of planet) * 15 degrees = 180
degrees offset to longitude, putting us back at Greenwich, with a longitude
of 0)

This would avoid the maths invalid function parameter, and give the sunrise
and sunset times not in GMT worldwide, but in the correct timezone for the
person doing the query.

I think a fully offline sun calculator can be accomplished, with two main
problems:

1: Country borders incorrectly assigned the wrong timezone.
2: Daylight Saving Time's are most likely needing to be user entered. (or
found via the running platforms API).

**Comment by JasperG** [comment]
The latitude and longitude (89 and 179) you are using are in the arctic circle.
The problem you are experiencing is related to the fact the sun never sets in summer, and never rises in winter at the given coordinates, including your test date ('2013-03-05UTC').

As far as I have taken time to read and understand your (rather lengthy) last article, I assume your issue is not at all related to timezones.

**Comment by mourner** [comment]
I believe so too, will reopen if it's an actual issue.

**Comment by Sarah-C** [comment]
Thanks!

**Comment by Sarah-C** [comment]
Cool. Have a good evening. Snacks for me now.

**Comment by rc1** [comment]
Hey, just my two cents... an invalid date as the return for this takes a bit of debugging to figure out what's going on. It would be good if it returned `null` or something.

What do you think? I can PR if you agree with the design.
