### ISSUE TITLE
Comparison to over data sources

### ISSUE THREAD

**Issue by davidtme** [mourner/suncalc#67]
I'm just double checking the data output is close to other data sources and I seem to be seeing something a bit odd

The following code:

```
var times = SunCalc.getTimes(new Date("08/mar/2016"), 53.4785216, -2.2499202);

console.log("sunrise", times.sunrise);
console.log("sunset", times.sunset);
```

Outputs:

```
sunrise Mon Mar 07 2016 06:43:25 GMT+0000 (GMT Standard Time)
sunset Mon Mar 07 2016 17:59:21 GMT+0000 (GMT Standard Time)
```

Which seems to be the wrong date

Also compared to http://www.sunrisesunset.com/ the sunrise is the day before and the sunset is the correct time but wrong date.

![image](https://cloud.githubusercontent.com/assets/1804141/13597973/38a95b60-e513-11e5-83dd-8c3f0b6b3d7d.png)

**Comment by mourner** [comment]
It's working as expected if you take timezones and how Date object works in JavaScript into account.

**Comment by davidtme** [comment]
Thank @mourner for the very fast response. I'm just wondering how I use it then (I'm running at GMT at the moment). Do I have to shift times around after it's been converted?

**Comment by mourner** [comment]
It calculates times according to your local timezone, and returns times symmetrically around solar noon closest to the time you pass to `getTimes`.

**Comment by davidtme** [comment]
@mourner on the http://suncalc.net/ it seems you can get 2 different sun rises depending on the time of day you visit the site which look to be what I'm getting in code:

http://suncalc.net/#/53.4785,-2.2499,11/2016.03.08/00:10 - 06:43 - sunrise
http://suncalc.net/#/53.4785,-2.2499,11/2016.03.08/00:11 - 06:41 - sunrise

**Comment by mourner** [comment]
@davidtme which is fully explained by my previous comment. 00:10 is closer to past day's solar noon, and 00:11 is closer to next day's solar noon, so sunrise results are different.

**Comment by davidtme** [comment]
@mourner so if I wanted to get the sun rise and sun set on the 8/mar/2016 for point 53.4785216, -2.2499202 what time would I need to pass into SunCalc.getTimes. (I was hoping it would match http://www.sunrisesunset.com or be very close)
