### ISSUE TITLE
Incorrect moon phase times

### ISSUE THREAD

**Issue by marcova84** [mourner/suncalc#68]
Hi,

Really appreciate the work you did on this library! One question: when I loop through every minute of March I get 23-3-2016 09:40:00 UTC as full moon date. When I search the internet I find the same date but 12:02 UTC as time. Do you know what causes this difference?

edit: I use SunCalc.getMoonIllumination(date) -> phase nearest to 0.5 to determine the full moon time.

Thanks in advance!

Best regards,

marcova84

**Comment by mourner** [comment]
Can you provide a full test case, e.g. with JSFiddle? I don't understand the issue.

**Comment by marcova84** [comment]
These times are nowhere to be found on the net. Am I doing something wrong?

https://jsfiddle.net/bg8Lc92f/

**Comment by dataglot** [comment]
I have also tried (binary searching) SunCalc to find the exact time of moon phases, for example the 23rd March 2016 full moon: https://jsfiddle.net/bhfwwzpq/1/.  This gives 09:06 GMT whereas http://www.timeanddate.com/moon/phases/ gives 12:00 GMT.

SunCalc's algorithm is probably good for the phase at a given day, but not accurate to the phase at a given time.  https://github.com/ryanseys/lune implements a different algorithm ("moontool.c" by John Walker) which more closely approximates exact phase times.

```
$ cat foo.js 
var lune = require('lune')
console.log(lune.phase_hunt(new Date(2016, 2, 23)).full_date)
$ node foo.js 
Wed Mar 23 2016 12:01:38 GMT+0000 (GMT)
```

**Comment by mourner** [comment]
> SunCalc's algorithm is probably good for the phase at a given day, but not accurate to the phase at a given time.

@dataglot you're correct. SunCalc has a nice simple approximation with just a few lines of code, but it's not good enough to precisely find the exact time of a certain moon phase. Lune.js looks like a much more sophisticated approach.
