### ISSUE TITLE
installing package via npm doesn't contain parallacticAngle

### ISSUE THREAD

**Issue by petroleumjelliffe** [mourner/suncalc#71]
The parallactic angle for the moon isn't returned when I install the suncalc npm package. 

I see the code in github, but that line is missing from the suncalc.js file in the node_modules folder.    

My package.json has this dependency:

```
"dependencies": {
    "suncalc": "^1.7.0"
}
```

**Comment by mourner** [comment]
Yeah, I should make a 1.8.0 release on NPM that includes the change. Meanwhile you can just specify `mourner/suncalc` as version so that it pulls from GitHub.

**Comment by mourner** [comment]
1.8.0 was released.
