### ISSUE TITLE
Plot the sun for one day

### ISSUE THREAD

**Issue by glittle** [mourner/suncalc#81]
Hi, Vladimir. This is a request, not an "issue"!

I would like to calculate the numbers needed to display a chart like this. (This example would be for an area when the night is longer than the day!)

![image](https://cloud.githubusercontent.com/assets/85186/21570741/331a2f1e-ce86-11e6-94e9-58eaab99403c.png)

I'm thinking that I likely need about 20 points to be able to plot the line. Could I step through the times from sunset to sunset and use `hourAngle` to do this? What would I need to pass as `h` for each time?

Thanks!!

**Comment by mourner** [comment]
It's hard to say from the chart but it looks like sun's altitude, returned from `getPosition` method.

**Comment by glittle** [comment]
Hi Vladimir,

Here's what I've ended up with, showing results for somewhere in Kansas, USA. This is done, as you suggested, by using `getPosition(t).altitude`.
![image](https://cloud.githubusercontent.com/assets/85186/21878683/1ee3e2a4-d851-11e6-96db-a9e2f26efc18.png)

I find it interesting that the curve at midnight is not the same as the one at noon.  Here's another view during the summer. I presume that it would be more pronounced the further north/south you go.
![image](https://cloud.githubusercontent.com/assets/85186/21878938/b9501ef6-d852-11e6-94c5-97fa0f0a3eae.png)

Here's what it is like around the equinox.
![image](https://cloud.githubusercontent.com/assets/85186/21878994/1b9cb0ec-d853-11e6-9fbd-7508f647936e.png)

(You don't need to reopen this issue... I just wanted to share my results with you!)

**Comment by mourner** [comment]
@glittle awesome, thanks for sharing! Is the curve consistent with the charts from other sources like https://www.timeanddate.com/?

**Comment by glittle** [comment]
That's a good question...

Here are the charts for my location for today - mine then timeanddate's. They are similar, but the first does seem to dip further down.
![image](https://cloud.githubusercontent.com/assets/85186/21894374/304c5ea4-d89c-11e6-9410-f407721102ef.png)
![image](https://cloud.githubusercontent.com/assets/85186/21894379/3a255584-d89c-11e6-8626-a4ab064cce4e.png)

However, the example they have on (https://www.timeanddate.com/astronomy/about-sun-moon.html) does have an asymmetrical shape more similar to mine:
![image](https://cloud.githubusercontent.com/assets/85186/21894471/98e390ea-d89c-11e6-837f-1fe222ed27d6.png)
