### ISSUE TITLE
Add sunBehindDawnHorizonDuration and sunBehindDuskHorizonDuration

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#85]
I think this information is important as for those wanting to see the sunrise or sunset, they could get the complete timeframe of the event ahead of their visit to the beach, bay, desert, whatever, so they could plan accordingly. That is, it happens so fast, every second counts, especially if you are taking pictures or a video. :)

"The time from when the sun first appears in the morning to when it is completely above the horizon (or the opposite in the evening) is about 2 minutes 45 seconds at the equinox. At the solstice or first day of summer and winter the time is about 3 minutes 15 seconds. " -- [i lost the link]

I would recommend returning the value in seconds.

**Comment by mourner** [comment]
As in #84, this is simply `sunriseEnd - sunrise` and `sunset - sunsetStart` —  I'm not sure I want to complicate the API with lots of derived properties.
