### ISSUE TITLE
Provide center/edge toggle when getting Sunrise/Sunset information

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#86]
Provide center/edge toggle when getting Sunrise/Sunset information
This was similarly done with Pyephem; http://rhodesmill.org/pyephem/rise-set.html#computing-twilight

**Comment by mourner** [comment]
This is taken into account by sunrise/sunset angle definitions — they both range from `-0.833` to `-0.3` sun altitude, accounting for atmosphere refraction.
