### ISSUE TITLE
Add support for 'one hour after sunset to one hour before sunrise' 

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#87]
'not sure how to reference this, but it may be a helpful feature to some use cases as it's third in line for levels of night flying restrictiveness:

"Three different concepts of "night" are referred to in the Federal Aviation Regulations in the US. These include the periods from
(1) sunset to sunrise,
(2) the end of evening civil twilight to the beginning of morning civil twilight (this is the "standard definition of night", given in FAR Section 1.1),
(3) **one hour after sunset to one hour before sunrise.**
These uses of night are listed in order of increasing restrictiveness. The end of evening civil twilight generally occurs less than one hour after sunset. AirNav is a good source for sunset and sunrise and evening civil twilight and morning civil twilight." -- https://en.wikipedia.org/wiki/Night_aviation_regulations_in_the_US

**Comment by mourner** [comment]
Once again, `new Date(sunset - 1000 * 60)`. I think we should leave this up to users.
