### ISSUE TITLE
isDay, isNight, isTwilight, etc.

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#88]
isDay (returns true or false)
isTwilight
isCivilTwilight
isNauticalTwilight
isAstronomicalTwilight
isBlueHour
isGoldenHour
isNight
isAviationNight
  -  "Night means the time between the end of evening civil twilight and the beginning of morning civil twilight, as published in the Air Almanac, converted to local time." -- http://bit.ly/2iAjV7p

**Comment by mourner** [comment]
I want to keep the API as simple as possible. Users can do it easily enough themselves, e.g. `date < sunset && date > sunrise` for `isDay1`.

**Comment by derWebdesigner** [comment]
I know this issue is quite old already but as a hint for others: Make sure to check if there is even a sunset, for example by checking `sunsetPos.azimuth == null`.
