### ISSUE TITLE
Varying resultant times between sunrise/sunset resources

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#89]
Given the same time and location,  times don't match among Sunrise/Sunset utilities.  Please verify that your utility is accurate.

Sunday UTC 6 September 2009
for atlanta (33.8, -84.4)
more specifically (33.766667, -84.416667)

USNO (http://bit.ly/2iPNelk) - (33.766667, -84.416667)
Sunrise: 2009/9/6 11:15:00 UTC
Sunset: 2009/9/6 23:56:00 UTC

sunrisesunsetlib-java - (33.766667, -84.416667)
Sunrise: 2009/9/6 11:15:00 UTC
Sunset: 2009/9/6 23:57:00 UTC

Pyephem (http://rhodesmill.org/pyephem/rise-set.html) - (33.8, -84.4)
Sunrise: 2009/9/6 11:14:57 UTC
Sunset: 2009/9/6 23:56:10 UTC

SunriseSunset (33.766667, -84.416667)
Sunrise: 2009/9/6 11:16:33 UTC
Sunset: 2009/9/6 23:58:17 UTC

http://api.sunrise-sunset.org/ (http://api.sunrise-sunset.org/json?lat=33.766667&lng=-84.416667&date=2009-09-06)
SunriseSunset (33.766667, -84.416667)
Sunrise: 2009/9/6 11:15:27 UTC
Sunset: 2009/9/6 23:55:58 UTC

**Comment by mourner** [comment]
Which of these results are from `suncalc`?

These kinds of libraries simply can't be accurate up to the seconds. They each do certain simplifications to make the calculation simpler, and don't account for some things like altitude or weather conditions. I'm not an astronomer; I wrote the code based on [this article](http://aa.quae.nl/en/reken/zonpositie.html), and will leave verifying the accuracy to someone else.
