### ISSUE TITLE
Create method to return magnetic direction for Sunrise and Sunset

### ISSUE THREAD

**Issue by robertjliguori** [mourner/suncalc#90]
Methods to return magnetic directions towards the sun when it is at the center of the horizon for sunrise and sunset would be swell.

This would be fantastic if I was waiting for the sun to come up with a magnetic compass, and not knowing where to look... an app could get this data for me. ALSO, one could set up a video camera with this info and when the sun passes the horizon, it would be perfectly centered. :)

Also consider Solar Noon and Solar Midinight

magneticDirectionSunrise
magneticDirectionSolarNoon
magneticDirectionSunset
magneticDirectionSolarMidnight

**Comment by mourner** [comment]
This is technically not possible within the scope of this library, because magnetic declination can't be calculated algorithmically — it can only be derived from a magnetic map. https://en.wikipedia.org/wiki/Magnetic_declination
