### ISSUE TITLE
How calculate lunar zodiac sign?

### ISSUE THREAD

**Issue by g00dv1n** [mourner/suncalc#93]
I need calculate lunar zodiac sign. How I can do this using suncalc?

**Comment by mourner** [comment]
I don't know to be honest. Does the zodiac sign depend on illumination or position in the sky?

**Comment by g00dv1n** [comment]
Положение Луны в знаке Зодиака наблюдается с точки зрения земного наблюдателя. В классическом Зодиаке 360 градусов, 12 знаков, в каждом знаке 30 градусов. Луна проходит 1 градус за 2 часа.
