### ISSUE TITLE
Issue with moonrise and moonset with some dates.

### ISSUE THREAD

**Issue by alberto-valladolid** [mourner/suncalc#95]
It give me undefined for some dates, like for example, 2019-01-26.

"<script type="text/javascript">
 var moontime = SunCalc.getMoonTimes(new Date("2019-01-26"), 40.42, -3.70); 
 document.write(moontime.rise);
</script>"

It give me undefined for 1-2 days per month.
¿Do you know why?

**Comment by mourner** [comment]
Moon does not necessarily always rise or set in all locations. Try comparing the results with https://www.timeanddate.com/moon/. I'll reopen the issue if it doesn't match with undefined rise/set.
