### ISSUE TITLE
Wrong time of sun set and moon set !

### ISSUE THREAD

**Issue by zyo00ody** [mourner/suncalc#96]
test this in suncalc

alert(SunCalc.getTimes(new Date("2013-07-08"), 34.0522,-118.2437).sunset);
alert(SunCalc.getMoonTimes(new Date("2013-07-08"), 34.0522,-118.2437).set);

not true

**Comment by mourner** [comment]
What values do you expect and what do you get?

**Comment by zyo00ody** [comment]
Sorry, there is no wrong, I was wrong. thank you mourner very much for this accurate script !

**Comment by zyo00ody** [comment]
Yes there are an error

alert(SunCalc.getTimes(new Date("2013-07-08"), 34.0522,-118.2437).sunset);
alert(SunCalc.getMoonTimes(new Date("2013-07-08"), 34.0522,-118.2437).set);

in this date and location the true difference between  Sun-set and Moon-set is 10 minutes,
But in suncalc it is 28 minutes !

**Comment by zyo00ody** [comment]
See this is the true time for 2013-07-08:

alert(SunCalc.getTimes(new Date("2013-07-08"), 34.0522,-118.2437).sunset);
alert(SunCalc.getMoonTimes(new Date("2013-07-09"), 34.0522,-118.2437).set);

When I add 1 day for moon times it is true. There are an error in getMoonTimes(). and not for all locations.

**Comment by zyo00ody** [comment]
I think there is an error with Timezone in getMoonTimes()

**Comment by zyo00ody** [comment]
compare it with this site
moonset: https://www.timeanddate.com/moon/usa/los-angeles?month=7&year=2013
sunset   : https://www.timeanddate.com/sun/usa/los-angeles?month=7&year=2013

**Comment by zyo00ody** [comment]
I think the problem from this in getMoonTimes()
`    if (inUTC) t.setUTCHours(0, 0, 0, 0);
    else t.setHours(0, 0, 0, 0);`

why it is not there in getTimes() also ?

**Comment by zyo00ody** [comment]
I don't know whats the problem
