### ISSUE TITLE
Convert altitude/azimuth into degree

### ISSUE THREAD

**Issue by caezdl** [mourner/suncalc#97]
Hi

Math isn't my forte and I'm trying to emulate the sun position for a design I'm currently working on. Does anybody knows a formula to convert the altitude and/or azimuth into a simple circle rotation with degrees? 

0º and 180º being the horizon and 90º being the zenith like this : 
![exemple](http://i.imgur.com/WqFYCl8.png)

I tried a simple radian conversion with solarNoon like so : `altitude * 180 / Math.PI` and got 66.47525185883474º where I expected 90º.

Thanks a lot

**Comment by mourner** [comment]
I'm not sure why you expected 90 in your case but `altitude * 180 / Math.PI` is right.
